<h3>This new page is generated by CRM/Webcamphoto/Page/WebcamPhoto.php</h3>

{* Example: Display a variable directly *}
<p>The current time is {$currentTime}</p>

{* Example: Display a translated string -- which happens to include a variable *}
<p>{ts 1=$currentTime}(In your native language) The current time is %1.{/ts}</p>

<div id="my_camera" style="height:240px;width:240px;"></div>

<div><img src="{$imgsrc}"></div>

{crmScript ext=com.jasontdc.webcamphoto file=webcamjs/webcam.js}
{crmScript ext=com.jasontdc.webcamphoto file=webcamphoto.js}
